apiVersion: v1
kind: Service
metadata:
  name: backend-data-service
  namespace: {{ .Values.namespace }}
  labels:
    app: backend-data
spec:
  selector:
    app: backend-data
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
