apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: backend-api
spec:
  selector:
    app: backend-api
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
