apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: {{ .Values.namespace }}
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
