apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: frontend-service
  port:
    targetPort: 8080
